version: 2

models:
  - name: dim_products
    description: Product dimension table following Kimball modeling
    columns:
      - name: product_key
        description: Surrogate key for the product dimension
        tests:
          - unique
          - not_null
      
      - name: product_asin
        description: Amazon Standard Identification Number - natural key
        tests:
          - not_null
      
      - name: product_sku
        description: Stock Keeping Unit - natural key
        tests:
          - not_null
      
      - name: product_style
        description: Style identifier of the product
      
      - name: product_category
        description: Category of the product
        tests:
          - not_null
      
      - name: product_size
        description: Size of the product
      
      - name: created_at
        description: Timestamp when this record was first created
        tests:
          - not_null
      
      - name: updated_at
        description: Timestamp when this record was last updated
        tests:
          - not_null

  - name: dim_dates
    description: Date dimension table with calendar and fiscal attributes
    columns:
      - name: date_key
        description: Primary key in YYYYMMDD format
        tests:
          - unique
          - not_null

      - name: full_date
        description: Full date in DATE format
        tests:
          - unique
          - not_null

      - name: year
        description: Calendar year
        tests:
          - not_null

      - name: month_number
        description: Month number (1-12)
        tests:
          - not_null
          - accepted_values:
              values: ['1','2','3','4','5','6','7','8','9','10','11','12']

      - name: month_name
        description: Month name
        tests:
          - not_null

      - name: year_month
        description: Year and month in YYYY-MM format
        tests:
          - not_null

      - name: day_of_month
        description: Day of month (1-31)
        tests:
          - not_null

      - name: day_of_week_number
        description: Day of week number (1=Sunday, 7=Saturday)
        tests:
          - not_null
          - accepted_values:
              values: ['1','2','3','4','5','6','7']

      - name: day_of_week_name
        description: Day of week name
        tests:
          - not_null

      - name: fiscal_year
        description: Fiscal year (starting April 1)
        tests:
          - not_null

      - name: is_weekend
        description: Boolean flag for weekend days
        tests:
          - not_null

      - name: is_holiday
        description: Boolean flag for holidays
        tests:
          - not_null

      - name: created_at
        description: Timestamp when this record was first created
        tests:
          - not_null

      - name: updated_at
        description: Timestamp when this record was last updated
        tests:
          - not_null
